name: Create Release and Upload Binaries

on:
  push:
    tags:
      - 'v*' # Push events to tags matching v*, e.g. v1.0, v20.15.10

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .
        env:
          CMAKE_PREFIX_PATH: ''

      - name: Build executable with PyInstaller
        run: pyinstaller RawAlchemy.spec

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RawAlchemy-windows
          path: dist/RawAlchemy.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Linux system dependencies
        run: sudo apt-get update && sudo apt-get install -y libraw-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .

      - name: Build executable with PyInstaller
        run: pyinstaller RawAlchemy.spec

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RawAlchemy-linux
          path: dist/RawAlchemy

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare Artifacts for Release
        run: |
          tag="${{ github.ref_name }}"
          mv artifacts/RawAlchemy-windows/RawAlchemy.exe "RawAlchemy-${tag}-windows.exe"
          mv artifacts/RawAlchemy-linux/RawAlchemy "RawAlchemy-${tag}-linux"
        shell: bash

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            RawAlchemy-*-windows.exe
            RawAlchemy-*-linux